# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/innowise_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://localhost:5432/innowise_db
spring.liquibase.user=postgres
spring.liquibase.password=postgres
spring.liquibase.default-schema=public

#jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis
spring.cache.type=redis
spring.cache.redis.time-to-live=30m
spring.cache.redis.cache-null-values=false
spring.cache.redis.key-prefix=cache:
spring.cache.redis.use-key-prefix=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000

spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=1

#active profile
spring.profiles.active=dev

#logback
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.com.example.tasks.userservice=DEBUG

#jackson
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false