SELECT 'CLEANUP STARTED' AS status;
TRUNCATE TABLE card_info CASCADE;
TRUNCATE TABLE users CASCADE;
ALTER SEQUENCE card_info_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;
SELECT 'CLEANUP FINISHED' AS status;
